/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'plaufer' at '27.09.14 15:54' with Gradle 2.1
 *
 * @author plaufer, @date 27.09.14 15:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
